version: "3.9"

services:
  db:
    image: postgres:16
    container_name: marksolution_db
    environment:
      POSTGRES_USER: markuser
      POSTGRES_PASSWORD: markpass
      POSTGRES_DB: marksolution
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: marksolution_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
